### ISSUE TITLE
Lack of workflow documentation for aruba_switch_ssh_cli module?

### ISSUE THREAD

**Issue by erishiamu** [aruba/aruba-switch-ansible#16]
Hello,

I was investigating leveraging this due to issues relying solely on the base api module to obtain a copy of the running config, specifically using the aruba_switch_ssh_cli. The inventory setup for this is considerably more involved than any other platform we've configured, and I do not see *any* documentation for the ssh modules for switch (or cx for that matter). 

We configured the inventory as directed for the switch branch1, but some questions have arisen.

1: The inventory has us create both host and group vars for these which include the username/password to use for ssh. However the examples in the [module itself](https://github.com/aruba/aruba-switch-ansible/blob/master/library/arubaos_switch_ssh_cli.py#L38) seem to expect that those be entered. are we able to reference them as "{{ ip }}" "{{ user }}" "{{ password }}" ? 

2: Our environment is *extremely* simple. We do not have large numbers of these switches, they're individual stacks with a single management IP attached to a vlan. Do we need to replicate the mac address named host/group_vars and the specific host, or should we be able to use a standard hosts.yml setup to pull in the inventory for this specific module. While attempting to run a playbook largely copied off of this: 
    - name: Check current Firmware Version
      arubaos_switch_ssh_cli:
        ip: "ip of siwtch"
        user: "username for authentication"
        password: "password for authentication"
        # command, can also be a list with mode changes
        show_command: ["show flash"]
      register: ssh_output

It is seeing the inventory hostname as the mac address but is not resolving that back to an IP, and is ignoring the IP specified in the playbook. Due to lacking an example or documentation I'm not clear how we need to be pulling in the info from the ./group_vars ./host_vars and ./inventory/hosts.yml files.

**Comment by tchiapuziowong** [comment]
Hi @erishiamu !
The documentation you're referring to is to replicate the workflow we provide not the module itself. In order to use the modules you don't have to set up the inventory as it is in this repository. I would suggest following this article that explains how to use the modules solely: [How to install/use CLI modules and tasks for Switch and CX in Ansible](https://community.arubanetworks.com/t5/Developer-Community/How-to-install-use-CLI-modules-and-tasks-for-Switch-and-CX-in/m-p/534333?search-action-id=130922522279&search-result-uid=534333)
